name: AstraMolecula
channels:
  - conda-forge
  - pytorch
dependencies:
  - aiohttp
  - bcrypt
  - cpuonly
  - fastapi
  - mamba
  - psycopg2
  - pip
  - python=3.10
  - python-jose
  - pytorch
  - rdkit=2022.03
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - uvicorn
  - pandas
  - numpy
  - boto3
  - pyyaml
  - pip:
    - mmpdb==2.1
    - squareup
    - python-multipart
