name: dockingVina
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.14
  - fastapi
  - uvicorn
  - apsw
  - pytorch
  - torchvision
  - torchaudio
  - pandas[version='>=2.3,<2.4']
  - numpy[version='>=2.2,<2.3']
  - vina
  - tqdm
  - matplotlib
  - seaborn
  - rdkit=2024.3.5
  - python-jose
  - cryptography
  - mysql-connector-python
  - bcrypt
  - pip:
      - mmpdb==2.1
